DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE CLASS_SESSION CASCADE CONSTRAINTS;
DROP TABLE TRAINER CASCADE CONSTRAINTS;
DROP TABLE CLASS_TYPE CASCADE CONSTRAINTS;

CREATE TABLE CLASS_TYPE (
    CLASS_TYPE_ID INTEGER PRIMARY KEY,
    CLASS_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    DURATION INTEGER NOT NULL,
    CONSTRAINT CHK_CLASS_TYPE_DURATION CHECK (DURATION > 0)
);

CREATE TABLE TRAINER (
    TRAINER_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    SPECIALISATION VARCHAR2(100),
    SESSION_RATE NUMBER(8,2) NOT NULL,
    CONSTRAINT CHK_TRAINER_RATE CHECK (SESSION_RATE >= 0)
);

CREATE TABLE CLASS_SESSION (
    SESSION_ID INTEGER PRIMARY KEY,
    ATTENDANCE_ID INTEGER,
    CLASS_TYPE_ID INTEGER NOT NULL,
    TRAINER_ID INTEGER NOT NULL,
    SESSION_DATE DATE NOT NULL,
    SESSION_START_TIME TIMESTAMP NOT NULL,
    SESSION_END_TIME TIMESTAMP NOT NULL,
    CONSTRAINT FK_CLASS_SESSION_ATTENDANCE FOREIGN KEY (ATTENDANCE_ID) REFERENCES ATTENDANCE(ATTENDANCE_ID),
    CONSTRAINT FK_CLASS_SESSION_CLASS_TYPE FOREIGN KEY (CLASS_TYPE_ID) REFERENCES CLASS_TYPE(CLASS_TYPE_ID),
    CONSTRAINT FK_CLASS_SESSION_TRAINER FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(TRAINER_ID),
    CONSTRAINT CHK_SESSION_TIME CHECK (SESSION_END_TIME > SESSION_START_TIME)
);

CREATE TABLE BOOKING (
    BOOKING_ID INTEGER PRIMARY KEY,
    MEMBER_ID INTEGER NOT NULL,
    SESSION_ID INTEGER NOT NULL,
    BOOKING_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT FK_BOOKING_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(Member_ID),
    CONSTRAINT FK_BOOKING_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CLASS_SESSION(SESSION_ID),
    CONSTRAINT CHK_BOOKING_STATUS CHECK (STATUS IN ('ACTIVE','CANCELLED','COMPLETED'))
);
--------indexes
CREATE INDEX IDX_CLASS_SESSION_ATTENDANCE ON CLASS_SESSION(ATTENDANCE_ID);
CREATE INDEX IDX_CLASS_SESSION_CLASS_TYPE ON CLASS_SESSION(CLASS_TYPE_ID);
CREATE INDEX IDX_CLASS_SESSION_TRAINER ON CLASS_SESSION(TRAINER_ID);
CREATE INDEX IDX_BOOKING_SESSION ON BOOKING(SESSION_ID);
CREATE INDEX IDX_BOOKING_MEMBER ON BOOKING(MEMBER_ID);
---------data
INSERT INTO CLASS_TYPE VALUES (1, 'Yoga', 'Relaxation and flexibility class', 60);
INSERT INTO CLASS_TYPE VALUES (2, 'Strength Training', 'Weight and muscle building class', 60);
INSERT INTO CLASS_TYPE VALUES (3, 'Cardio Fitness', 'Heart and endurance training class', 45);

INSERT INTO TRAINER VALUES (1, 'John', 'Smith', 'Yoga', 250.00);
INSERT INTO TRAINER VALUES (2, 'Sarah', 'Brown', 'Strength Training', 300.00);
INSERT INTO TRAINER VALUES (3, 'Mike', 'Johnson', 'Cardio Fitness', 280.00);

INSERT INTO CLASS_SESSION VALUES (1, NULL, 1, 1, DATE '2026-05-01', TIMESTAMP '2026-05-01 09:00:00', TIMESTAMP '2026-05-01 10:00:00');
INSERT INTO CLASS_SESSION VALUES (2, NULL, 2, 2, DATE '2026-05-02', TIMESTAMP '2026-05-02 10:00:00', TIMESTAMP '2026-05-02 11:00:00');
INSERT INTO CLASS_SESSION VALUES (3, NULL, 3, 3, DATE '2026-05-03', TIMESTAMP '2026-05-03 08:00:00', TIMESTAMP '2026-05-03 08:45:00');

INSERT INTO BOOKING VALUES (1, 101, 1, SYSDATE, 'ACTIVE');
INSERT INTO BOOKING VALUES (2, 102, 2, SYSDATE, 'COMPLETED');
INSERT INTO BOOKING VALUES (3, 103, 3, SYSDATE, 'ACTIVE');
--------view
CREATE VIEW SESSION_VIEW AS
SELECT 
    CS.SESSION_ID,
    CT.CLASS_NAME,
    T.FIRST_NAME || ' ' || T.LAST_NAME AS TRAINER_NAME,
    CS.SESSION_DATE,
    CS.SESSION_START_TIME,
    CS.SESSION_END_TIME
FROM CLASS_SESSION CS
JOIN CLASS_TYPE CT ON CS.CLASS_TYPE_ID = CT.CLASS_TYPE_ID
JOIN TRAINER T ON CS.TRAINER_ID = T.TRAINER_ID;

CREATE VIEW BOOKING_VIEW AS
SELECT 
    B.BOOKING_ID,
    B.MEMBER_ID,
    CS.SESSION_ID,
    CT.CLASS_NAME,
    CS.SESSION_DATE,
    B.STATUS
FROM BOOKING B
JOIN CLASS_SESSION CS ON B.SESSION_ID = CS.SESSION_ID
JOIN CLASS_TYPE CT ON CS.CLASS_TYPE_ID = CT.CLASS_TYPE_ID;
------------------------------------------------------------------AM-------------------
CREATE VIEW Member_View AS
SELECT Member_ID, First_Name, Last_Name, Phone, Email, Membership_Status
FROM MEMBER;

CREATE VIEW Member_Package_View AS
SELECT Package_ID, Package_Name, Duration, Monthly_Fee
FROM MEMBER_PACKAGE;

CREATE VIEW Payment_Info_View AS
SELECT Payment_ID, Amount_Paid, Outstanding_Amount, Payment_Method, Payment_Date
FROM PAYMENT_INFO;

CREATE VIEW Payment_View AS
SELECT Member_ID, Payment_ID
FROM PAYMENT;

CREATE VIEW Member_Payment_View AS
SELECT M.Member_ID, M.First_Name, M.Last_Name,
       PI.Payment_ID, PI.Amount_Paid, PI.Outstanding_Amount, PI.Payment_Date
FROM MEMBER M, PAYMENT P, PAYMENT_INFO PI
WHERE M.Member_ID = P.Member_ID
AND P.Payment_ID = PI.Payment_ID;


CREATE INDEX idx_member_package ON MEMBER (Package_ID);

CREATE INDEX idx_payment_member ON PAYMENT (Member_ID);

CREATE INDEX idx_payment_paymentid ON PAYMENT (Payment_ID);

CREATE INDEX idx_paymentinfo_date ON PAYMENT_INFO (Payment_Date);


INSERT INTO MEMBER_PACKAGE VALUES (1, 'Basic Package', 1, 250.00);
INSERT INTO MEMBER_PACKAGE VALUES (2, 'Standard Package', 3, 600.00);
INSERT INTO MEMBER_PACKAGE VALUES (3, 'Premium Package', 6, 1000.00);

INSERT INTO MEMBER VALUES (101, 1, 'Thabo', 'Mokoena', '0712345678', 'thabo@gmail.com', DATE '2026-01-01', DATE '2026-02-01', 'Active');
INSERT INTO MEMBER VALUES (102, 2, 'Lerato', 'Dlamini', '0723456789', 'lerato@gmail.com', DATE '2026-01-10', DATE '2026-04-10', 'Active');
INSERT INTO MEMBER VALUES (103, 3, 'Sipho', 'Nkosi', '0734567890', 'sipho@gmail.com', DATE '2026-02-01', DATE '2026-08-01', 'Active');

INSERT INTO PAYMENT_INFO VALUES (201, 250.00, 0.00, 'Cash', DATE '2026-01-01');
INSERT INTO PAYMENT_INFO VALUES (202, 300.00, 300.00, 'Card', DATE '2026-01-10');
INSERT INTO PAYMENT_INFO VALUES (203, 1000.00, 0.00, 'EFT', DATE '2026-02-01');

INSERT INTO PAYMENT VALUES (101, 201);
INSERT INTO PAYMENT VALUES (102, 202);
INSERT INTO PAYMENT VALUES (103, 203);

COMMIT;

SELECT * FROM MEMBER_PACKAGE;
SELECT * FROM MEMBER;
SELECT * FROM PAYMENT_INFO;
SELECT * FROM PAYMENT;



CREATE TABLE MAINTENANCE (
    Maintenance_ID   NUMBER(5) PRIMARY KEY,
    Equipment_ID     NUMBER(5),
    Technician_ID    NUMBER(5),
    Maintenance_Date DATE,
    Service_Type     VARCHAR2(50),
    Repair_Cost      NUMBER(8,2),

    CONSTRAINT fk_maintenance_equipment
        FOREIGN KEY (Equipment_ID)
        REFERENCES EQUIPMENT(Equipment_ID),

    CONSTRAINT fk_maintenance_technician
        FOREIGN KEY (Technician_ID)
        REFERENCES TECHNICIAN(Technician_ID)
);

